export type SeedTopicProgress = {
  completed: boolean;
  completedAt?: number;
  bestScore: number;
  totalXp: number;
  attempts: number;
  lastPlayedAt?: number;
};

export type SeedUser = {
  email: string;
  name: string;
  bio: string;
  interests: string[];
  dailyGoalMin: number;
  isFriend: boolean;
  totalXp: number;
  weeklyXp: number;
  streakDays: number;
  longestStreak: number;
  topicIds: string[];
  achievementIds: string[];
  notifications: Array<{
    type: string;
    title: string;
    message: string;
    icon: string;
    color: string;
    read: boolean;
    daysAgo: number;
  }>;
};

const TOPIC_POOL = [
  'sum',
  'sub',
  'mul',
  'div',
  'simplify',
  'linear',
  'speed',
  'force',
  'kinetic',
  'tags',
  'titles',
  'paragraphs',
  'vars',
  'isolate',
  'distance',
  'time',
  'accel',
  'potential',
  'links',
  'images',
] as const;

export function buildTopics(topicIds: string[], baseXp: number): Record<string, SeedTopicProgress> {
  const topics: Record<string, SeedTopicProgress> = {};
  const now = Date.now();

  topicIds.forEach((topicId, index) => {
    const attempts = 1 + (index % 4);
    const bestScore = 62 + ((index * 17 + baseXp) % 38);
    const topicXp = Math.floor(baseXp / Math.max(topicIds.length, 1));
    topics[topicId] = {
      completed: bestScore >= 60,
      completedAt: now - (index + 1) * 86_400_000,
      bestScore,
      totalXp: topicXp,
      attempts,
      lastPlayedAt: now - index * 43_200_000,
    };
  });

  return topics;
}

export const SEED_USERS: SeedUser[] = [
  {
    email: 'valentina.morales@gmail.com',
    name: 'Valentina Morales',
    bio: 'Estudiante de prepa apasionada por las matemáticas y la física.',
    interests: ['math', 'physics'],
    dailyGoalMin: 20,
    isFriend: true,
    totalXp: 48_750,
    weeklyXp: 6_420,
    streakDays: 34,
    longestStreak: 41,
    topicIds: TOPIC_POOL.slice(0, 14),
    achievementIds: ['launch', 'first-steps', 'xp-500', 'xp-2000', 'level-5', 'level-10', 'streak-7', 'streak-30', 'mathlete'],
    notifications: [
      {
        type: 'streak',
        title: 'Racha de 34 días',
        message: 'Valentina, llevas más de un mes practicando seguido. ¡Increíble constancia!',
        icon: 'local-fire-department',
        color: '#ffb4ab',
        read: false,
        daysAgo: 0,
      },
      {
        type: 'achievement',
        title: 'Logro: Mathlete',
        message: 'Completaste el módulo de Álgebra básica. Sigue así.',
        icon: 'emoji-events',
        color: '#cfbdff',
        read: true,
        daysAgo: 2,
      },
    ],
  },
  {
    email: 'diego.herrera@outlook.com',
    name: 'Diego Herrera',
    bio: 'Me gusta programar y resolver problemas de lógica.',
    interests: ['code', 'math'],
    dailyGoalMin: 15,
    isFriend: true,
    totalXp: 41_200,
    weeklyXp: 5_890,
    streakDays: 21,
    longestStreak: 28,
    topicIds: TOPIC_POOL.slice(2, 15),
    achievementIds: ['launch', 'xp-500', 'xp-2000', 'level-5', 'level-10', 'streak-7', 'code'],
    notifications: [
      {
        type: 'lesson',
        title: 'Nueva lección en Programación',
        message: 'Prueba "Variables y expresiones" — ideal para reforzar tu racha.',
        icon: 'menu-book',
        color: '#51d5ff',
        read: false,
        daysAgo: 1,
      },
    ],
  },
  {
    email: 'camila.rios@hotmail.com',
    name: 'Camila Ríos',
    bio: 'Aprendiendo inglés para estudiar en el extranjero.',
    interests: ['english', 'math'],
    dailyGoalMin: 10,
    isFriend: true,
    totalXp: 36_800,
    weeklyXp: 4_950,
    streakDays: 18,
    longestStreak: 22,
    topicIds: ['sum', 'sub', 'tags', 'titles', 'paragraphs', 'links', 'images', 'mul', 'simplify'],
    achievementIds: ['launch', 'first-steps', 'xp-500', 'xp-2000', 'level-5', 'streak-3', 'streak-7', 'polyglot'],
    notifications: [
      {
        type: 'welcome',
        title: '¡Bienvenida de nuevo!',
        message: 'Tienes 3 lecciones pendientes esta semana. ¿Empezamos?',
        icon: 'celebration',
        color: '#cfbdff',
        read: false,
        daysAgo: 0,
      },
    ],
  },
  {
    email: 'santiago.vega@yahoo.com.mx',
    name: 'Santiago Vega',
    bio: 'Fan de la física clásica y los retos semanales.',
    interests: ['physics', 'math'],
    dailyGoalMin: 25,
    isFriend: false,
    totalXp: 33_400,
    weeklyXp: 4_710,
    streakDays: 15,
    longestStreak: 19,
    topicIds: ['speed', 'distance', 'time', 'force', 'accel', 'kinetic', 'potential', 'sum', 'linear'],
    achievementIds: ['launch', 'xp-500', 'xp-2000', 'level-5', 'streak-7', 'einstein'],
    notifications: [
      {
        type: 'system',
        title: 'Reto semanal activo',
        message: 'Estás a 290 XP de entrar al top 3 global. ¡Un empujón más!',
        icon: 'leaderboard',
        color: '#51d5ff',
        read: false,
        daysAgo: 0,
      },
    ],
  },
  {
    email: 'isabella.cruz@gmail.com',
    name: 'Isabella Cruz',
    bio: 'Practicando todos los días antes de clase.',
    interests: ['math', 'english'],
    dailyGoalMin: 15,
    isFriend: true,
    totalXp: 29_650,
    weeklyXp: 3_980,
    streakDays: 27,
    longestStreak: 27,
    topicIds: TOPIC_POOL.slice(0, 10),
    achievementIds: ['launch', 'first-steps', 'xp-500', 'xp-2000', 'level-5', 'streak-7'],
    notifications: [
      {
        type: 'streak',
        title: 'Racha personal récord',
        message: 'Llevas 27 días seguidos. No dejes que se apague hoy.',
        icon: 'local-fire-department',
        color: '#ffb4ab',
        read: true,
        daysAgo: 1,
      },
    ],
  },
  {
    email: 'mateo.silva@proton.me',
    name: 'Mateo Silva',
    bio: 'Construyendo bases sólidas en álgebra.',
    interests: ['math'],
    dailyGoalMin: 10,
    isFriend: false,
    totalXp: 24_100,
    weeklyXp: 3_240,
    streakDays: 9,
    longestStreak: 14,
    topicIds: ['sum', 'sub', 'mul', 'div', 'simplify', 'vars', 'isolate', 'linear'],
    achievementIds: ['launch', 'xp-500', 'xp-2000', 'level-5', 'streak-3', 'mathlete'],
    notifications: [
      {
        type: 'lesson',
        title: 'Repaso sugerido',
        message: 'Tu último intento en "Ecuaciones lineales" fue hace 3 días.',
        icon: 'menu-book',
        color: '#51d5ff',
        read: false,
        daysAgo: 3,
      },
    ],
  },
  {
    email: 'renata.paredes@icloud.com',
    name: 'Renata Paredes',
    bio: 'Combino HTML con matemáticas para proyectos escolares.',
    interests: ['code', 'math', 'english'],
    dailyGoalMin: 20,
    isFriend: true,
    totalXp: 21_850,
    weeklyXp: 2_870,
    streakDays: 11,
    longestStreak: 16,
    topicIds: ['tags', 'titles', 'paragraphs', 'links', 'images', 'sum', 'sub', 'vars'],
    achievementIds: ['launch', 'xp-500', 'xp-2000', 'level-5', 'code'],
    notifications: [
      {
        type: 'achievement',
        title: 'Nuevo logro desbloqueado',
        message: 'Conseguiste "Code Cadet" por completar 3 temas de programación.',
        icon: 'emoji-events',
        color: '#cfbdff',
        read: false,
        daysAgo: 2,
      },
    ],
  },
  {
    email: 'andres.mendoza@gmail.com',
    name: 'Andrés Mendoza',
    bio: 'Compitiendo con amigos en el ranking semanal.',
    interests: ['math', 'physics', 'code'],
    dailyGoalMin: 30,
    isFriend: true,
    totalXp: 19_400,
    weeklyXp: 2_650,
    streakDays: 6,
    longestStreak: 12,
    topicIds: TOPIC_POOL.slice(0, 9),
    achievementIds: ['launch', 'first-steps', 'xp-500', 'xp-2000', 'level-5', 'streak-3'],
    notifications: [
      {
        type: 'system',
        title: 'Subiste 2 puestos',
        message: 'Ahora estás en el puesto #7 del ranking semanal.',
        icon: 'trending-up',
        color: '#51d5ff',
        read: true,
        daysAgo: 0,
      },
    ],
  },
  {
    email: 'lucia.torres@outlook.com',
    name: 'Lucía Torres',
    bio: 'Estudio en las tardes después del trabajo.',
    interests: ['english', 'code'],
    dailyGoalMin: 5,
    isFriend: false,
    totalXp: 16_720,
    weeklyXp: 2_180,
    streakDays: 4,
    longestStreak: 9,
    topicIds: ['tags', 'titles', 'paragraphs', 'links', 'sum', 'sub'],
    achievementIds: ['launch', 'xp-500', 'xp-2000', 'level-5', 'polyglot'],
    notifications: [
      {
        type: 'welcome',
        title: 'Meta diaria cumplida',
        message: 'Completaste tus 5 minutos de hoy. Buen trabajo, Lucía.',
        icon: 'celebration',
        color: '#cfbdff',
        read: false,
        daysAgo: 0,
      },
    ],
  },
  {
    email: 'javier.romero@hotmail.com',
    name: 'Javier Romero',
    bio: 'Preparándome para olimpiadas de matemáticas.',
    interests: ['math'],
    dailyGoalMin: 30,
    isFriend: false,
    totalXp: 14_300,
    weeklyXp: 1_920,
    streakDays: 13,
    longestStreak: 13,
    topicIds: ['sum', 'sub', 'mul', 'div', 'simplify', 'vars', 'isolate', 'linear'],
    achievementIds: ['launch', 'first-steps', 'xp-500', 'xp-2000', 'streak-7'],
    notifications: [
      {
        type: 'lesson',
        title: 'Desafío recomendado',
        message: 'Intenta "Multiplicación de fracciones" para subir tu mejor puntaje.',
        icon: 'menu-book',
        color: '#51d5ff',
        read: true,
        daysAgo: 4,
      },
    ],
  },
  {
    email: 'fernanda.aguilar@gmail.com',
    name: 'Fernanda Aguilar',
    bio: 'Me encantan las lecciones cortas de física.',
    interests: ['physics', 'math'],
    dailyGoalMin: 15,
    isFriend: true,
    totalXp: 12_600,
    weeklyXp: 1_740,
    streakDays: 8,
    longestStreak: 11,
    topicIds: ['speed', 'distance', 'time', 'force', 'accel', 'sum'],
    achievementIds: ['launch', 'xp-500', 'xp-2000', 'level-5', 'einstein'],
    notifications: [
      {
        type: 'streak',
        title: 'Mantén la racha',
        message: 'Practica hoy para no perder tus 8 días consecutivos.',
        icon: 'local-fire-department',
        color: '#ffb4ab',
        read: false,
        daysAgo: 0,
      },
    ],
  },
  {
    email: 'roberto.nunez@yahoo.com',
    name: 'Roberto Núñez',
    bio: 'Aprendo programación web desde cero.',
    interests: ['code'],
    dailyGoalMin: 10,
    isFriend: false,
    totalXp: 9_850,
    weeklyXp: 1_320,
    streakDays: 3,
    longestStreak: 7,
    topicIds: ['tags', 'titles', 'paragraphs', 'links', 'images'],
    achievementIds: ['launch', 'xp-500', 'xp-2000', 'code'],
    notifications: [
      {
        type: 'achievement',
        title: 'XP Hunter',
        message: 'Superaste los 500 XP totales. Sigue acumulando experiencia.',
        icon: 'emoji-events',
        color: '#cfbdff',
        read: true,
        daysAgo: 5,
      },
    ],
  },
  {
    email: 'paula.estrada@outlook.com',
    name: 'Paula Estrada',
    bio: 'Practicando inglés técnico para la universidad.',
    interests: ['english', 'code'],
    dailyGoalMin: 20,
    isFriend: true,
    totalXp: 8_200,
    weeklyXp: 1_050,
    streakDays: 5,
    longestStreak: 8,
    topicIds: ['tags', 'titles', 'paragraphs', 'links', 'sum'],
    achievementIds: ['launch', 'xp-500', 'xp-2000', 'polyglot'],
    notifications: [
      {
        type: 'system',
        title: 'Contenido nuevo',
        message: 'Hay 2 lecciones nuevas de Inglés disponibles en Explorar.',
        icon: 'system-update',
        color: '#51d5ff',
        read: false,
        daysAgo: 1,
      },
    ],
  },
  {
    email: 'emilio.gutierrez@gmail.com',
    name: 'Emilio Gutiérrez',
    bio: 'Retomando el estudio después de vacaciones.',
    interests: ['math', 'physics'],
    dailyGoalMin: 10,
    isFriend: false,
    totalXp: 6_450,
    weeklyXp: 890,
    streakDays: 2,
    longestStreak: 5,
    topicIds: ['sum', 'sub', 'speed', 'distance'],
    achievementIds: ['launch', 'xp-500', 'streak-3'],
    notifications: [
      {
        type: 'welcome',
        title: '¡Qué bueno verte de vuelta!',
        message: 'Retoma con una lección corta de 10 minutos.',
        icon: 'celebration',
        color: '#cfbdff',
        read: false,
        daysAgo: 0,
      },
    ],
  },
  {
    email: 'daniela.ortiz@hotmail.com',
    name: 'Daniela Ortiz',
    bio: 'Estudio en grupo con compañeros del salón.',
    interests: ['math', 'english'],
    dailyGoalMin: 15,
    isFriend: false,
    totalXp: 5_100,
    weeklyXp: 720,
    streakDays: 7,
    longestStreak: 10,
    topicIds: ['sum', 'sub', 'mul', 'tags', 'titles'],
    achievementIds: ['launch', 'xp-500', 'first-steps', 'streak-7'],
    notifications: [
      {
        type: 'lesson',
        title: 'Lección en progreso',
        message: 'Dejaste "Multiplicación básica" a medias. ¿Continuamos?',
        icon: 'menu-book',
        color: '#51d5ff',
        read: true,
        daysAgo: 2,
      },
    ],
  },
  {
    email: 'gabriel.pena@proton.me',
    name: 'Gabriel Peña',
    bio: 'Quiero dominar ecuaciones antes del examen.',
    interests: ['math'],
    dailyGoalMin: 25,
    isFriend: false,
    totalXp: 3_780,
    weeklyXp: 540,
    streakDays: 1,
    longestStreak: 6,
    topicIds: ['sum', 'vars', 'isolate', 'linear'],
    achievementIds: ['launch', 'xp-500'],
    notifications: [
      {
        type: 'streak',
        title: 'Primera racha',
        message: 'Llevas 1 día. Vuelve mañana para empezar una racha real.',
        icon: 'local-fire-department',
        color: '#ffb4ab',
        read: false,
        daysAgo: 0,
      },
    ],
  },
  {
    email: 'mariana.flores@gmail.com',
    name: 'Mariana Flores',
    bio: 'Empecé hace poco pero voy constante.',
    interests: ['english', 'math'],
    dailyGoalMin: 5,
    isFriend: true,
    totalXp: 2_350,
    weeklyXp: 410,
    streakDays: 4,
    longestStreak: 4,
    topicIds: ['sum', 'tags', 'titles'],
    achievementIds: ['launch', 'xp-500'],
    notifications: [
      {
        type: 'achievement',
        title: 'Despegue completado',
        message: 'Mariana, completaste tu primer ejercicio. ¡Gran inicio!',
        icon: 'emoji-events',
        color: '#cfbdff',
        read: true,
        daysAgo: 6,
      },
    ],
  },
  {
    email: 'ricardo.salinas@icloud.com',
    name: 'Ricardo Salinas',
    bio: 'Explorando todos los cursos poco a poco.',
    interests: ['math', 'physics', 'code', 'english'],
    dailyGoalMin: 15,
    isFriend: false,
    totalXp: 1_680,
    weeklyXp: 280,
    streakDays: 2,
    longestStreak: 3,
    topicIds: ['sum', 'speed', 'tags'],
    achievementIds: ['launch'],
    notifications: [
      {
        type: 'system',
        title: 'Tip del día',
        message: 'Practica 15 min diarios para ver resultados en 2 semanas.',
        icon: 'lightbulb',
        color: '#51d5ff',
        read: true,
        daysAgo: 3,
      },
    ],
  },
  {
    email: 'alejandra.ibarra@outlook.com',
    name: 'Alejandra Ibarra',
    bio: 'Usando Level Loop en el camino a la escuela.',
    interests: ['math', 'english'],
    dailyGoalMin: 10,
    isFriend: false,
    totalXp: 980,
    weeklyXp: 190,
    streakDays: 1,
    longestStreak: 2,
    topicIds: ['sum', 'sub'],
    achievementIds: ['launch'],
    notifications: [
      {
        type: 'welcome',
        title: 'Bienvenida a Level Loop',
        message: 'Completa tu primera lección para ganar XP extra.',
        icon: 'celebration',
        color: '#cfbdff',
        read: false,
        daysAgo: 0,
      },
    ],
  },
  {
    email: 'hugo.delgado@gmail.com',
    name: 'Hugo Delgado',
    bio: 'Recién registrado, emocionado por empezar.',
    interests: ['code'],
    dailyGoalMin: 10,
    isFriend: false,
    totalXp: 420,
    weeklyXp: 420,
    streakDays: 1,
    longestStreak: 1,
    topicIds: ['tags'],
    achievementIds: ['launch'],
    notifications: [
      {
        type: 'welcome',
        title: '¡Hola, Hugo!',
        message: 'Tu primera misión te espera en Programación → Etiquetas HTML.',
        icon: 'celebration',
        color: '#cfbdff',
        read: false,
        daysAgo: 0,
      },
      {
        type: 'lesson',
        title: 'Primera lección',
        message: 'Completa "Etiquetas básicas" para desbloquear tu primer logro.',
        icon: 'menu-book',
        color: '#51d5ff',
        read: false,
        daysAgo: 0,
      },
    ],
  },
];
